/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2015-06-13 17:59:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.rule;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class rules_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#CCCC99\">\r\n");
      out.write("<h3>第一章　总则</h3><br>\r\n");
      out.write("\r\n");
      out.write("第一条　为加强药品监督管理，规范药品流通秩序，保证药品质量，根据《中华人民共和国药品管理法》（以下简称《药品管理法》）、《中华人民共和国药品管理法实施条例》（以下简称《药品管理法实施条例》）和有关法律、法规的规定，制定本办法。<br><br>\r\n");
      out.write("第二条　在中华人民共和国境内从事药品购销及监督管理的单位或者个人，应当遵守本办法。<br><br>\r\n");
      out.write("第三条　药品生产、经营企业、医疗机构应当对其生产、经营、使用的药品质量负责。\r\n");
      out.write("药品生产、经营企业在确保药品质量安全的前提下，应当适应现代药品流通发展方向，进行改革和创新。<br><br>\r\n");
      out.write("第四条　药品监督管理部门鼓励个人和组织对药品流通实施社会监督。对违反本办法的行为，任何个人和组织都有权向药品监督管理部门举报和控告。<br><br>\r\n");
      out.write("<h3>第二章 药品生产、经营企业购销的监督管理</h3><br>\r\n");
      out.write("\r\n");
      out.write("第五条　药品生产、经营企业对其药品购销行为负责，对其销售人员或设立的办事机构以本企业名义从事的药品购销行为承担法律责任。<br><br>\r\n");
      out.write("第六条　药品生产、经营企业应当对其购销人员进行药品相关的法律、法规和专业知识培训，建立培训档案，培训档案中应当记录培训时间、地点、内容及接受培训的人员。<br><br>\r\n");
      out.write("第七条　药品生产、经营企业应当加强对药品销售人员的管理，并对其销售行为作出具体规定。<br><br>\r\n");
      out.write("第八条　药品生产、经营企业不得在经药品监督管理部门核准的地址以外的场所储存或者现货销售药品。<br><br>\r\n");
      out.write("第九条　药品生产企业只能销售本企业生产的药品，不得销售本企业受委托生产的或者他人生产的药品。<br><br>\r\n");
      out.write("第十条　药品生产企业、药品批发企业销售药品时，应当提供下列资料：<br><br>\r\n");
      out.write("（一）加盖本企业原印章的《药品生产许可证》或《药品经营许可证》和营业执照的复印件；<br><br>\r\n");
      out.write("（二）加盖本企业原印章的所销售药品的批准证明文件复印件；<br><br>\r\n");
      out.write("（三）销售进口药品的，按照国家有关规定提供相关证明文件。<br><br>\r\n");
      out.write("第十一条　药品生产企业、药品批发企业销售药品时，应当开具标明供货单位名称、药品名称、生产厂商、批号、数量、价格等内容的销售凭证。\r\n");
      out.write("药品零售企业销售药品时，应当开具标明药品名称、生产厂商、数量、价格、批号等内容的销售凭证。<br><br>\r\n");
      out.write("第十二条　药品生产、经营企业采购药品时，应按本办法第十条规定索取、查验、留存供货企业有关证件、资料，按本办法第十一条规定索取、留存销售凭证。\r\n");
      out.write("药品生产、经营企业按照本条前款规定留存的资料和销售凭证，应当保存至超过药品有效期1年，但不得少于3年。<br><br>\r\n");
      out.write("第十三条　药品生产、经营企业知道或者应当知道他人从事无证生产、经营药品行为的，不得为其提供药品。<br><br>\r\n");
      out.write("第十四条　药品生产、经营企业不得为他人以本企业的名义经营药品提供场所，或者资质证明文件，或者票据等便利条件。<br><br>\r\n");
      out.write("第十五条　药品生产、经营企业不得以展示会、博览会、交易会、订货会、产品宣传会等方式现货销售药品。<br><br>\r\n");
      out.write("第十六条　药品经营企业不得购进和销售医疗机构配制的制剂。<br><br>\r\n");
      out.write("第十七条　未经药品监督管理部门审核同意，药品经营企业不得改变经营方式。\r\n");
      out.write("药品经营企业应当按照《药品经营许可证》许可的经营范围经营药品。<br><br>\r\n");
      out.write("第十八条　药品零售企业应当按照国家食品药品监督管理局药品分类管理规定的要求，凭处方销售处方药。\r\n");
      out.write("经营处方药和甲类非处方药的药品零售企业，执业药师或者其他依法经资格认定的药学技术人员不在岗时，应当挂牌告知，并停止销售处方药和甲类非处方药。\r\n");
      out.write("第十九条　药品说明书要求低温、冷藏储存的药品，药品生产、经营企业应当按照有关规定，使用低温、冷藏设施设备运输和储存。\r\n");
      out.write("药品监督管理部门发现药品生产、经营企业违反本条前款规定的，应当立即查封、扣押所涉药品，并依法进行处理。<br><br>\r\n");
      out.write("第二十条　药品生产、经营企业不得以搭售、买药品赠药品、买商品赠药品等方式向公众赠送处方药或者甲类非处方药。<br><br>\r\n");
      out.write("第二十一条　药品生产、经营企业不得采用邮售、互联网交易等方式直接向公众销售处方药。<br><br>\r\n");
      out.write("第二十二条　禁止非法收购药品。<br><br>\r\n");
      out.write("<h3>第三章　医疗机构购进、储存药品的监督管理</h3><br>\r\n");
      out.write("\r\n");
      out.write("第二十三条　医疗机构设置的药房，应当具有与所使用药品相适应的场所、设备、仓储设施和卫生环境，配备相应的药学技术人员，并设立药品质量管理机构或者配备质量管理人员，建立药品保管制度。<br><br>\r\n");
      out.write("第二十四条　医疗机构购进药品时，应当按照本办法第十二条规定，索取、查验、保存供货企业有关证件、资料、票据。<br><br>\r\n");
      out.write("第二十五条　医疗机构购进药品，必须建立并执行进货检查验收制度，并建有真实完整的药品购进记录。药品购进记录必须注明药品的通用名称、生产厂商（中药材标明产地）、剂型、规格、批号、生产日期、有效期、批准文号、供货单位、数量、价格、购进日期。\r\n");
      out.write("药品购进记录必须保存至超过药品有效期1年，但不得少于3年。<br><br>\r\n");
      out.write("第二十六条　医疗机构储存药品，应当制订和执行有关药品保管、养护的制度，并采取必要的冷藏、防冻、防潮、避光、通风、防火、防虫、防鼠等措施，保证药品质量。\r\n");
      out.write("医疗机构应当将药品与非药品分开存放；中药材、中药饮片、化学药品、中成药应分别储存、分类存放。<br><br>\r\n");
      out.write("第二十七条　医疗机构和计划生育技术服务机构不得未经诊疗直接向患者提供药品。<br><br>\r\n");
      out.write("第二十八条　医疗机构不得采用邮售、互联网交易等方式直接向公众销售处方药。<br><br>\r\n");
      out.write("第二十九条　医疗机构以集中招标方式采购药品的，应当遵守《药品管理法》、《药品管理法实施条例》及本办法的有关规定。<br><br>\r\n");
      out.write("<h3>第四章　法律责任</h3><br>\r\n");
      out.write("\r\n");
      out.write("第三十条　有下列情形之一的，责令限期改正，给予警告；逾期不改正的，处以5000元以上2万元以下的罚款：<br><br>\r\n");
      out.write("（一）药品生产、经营企业违反本办法第六条规定的；<br><br>\r\n");
      out.write("（二）药品生产、批发企业违反本办法第十一条第一款规定的；<br><br>\r\n");
      out.write("（三）药品生产、经营企业违反本办法第十二条，未按照规定留存有关资料、销售凭证的。<br><br>\r\n");
      out.write("第三十一条　药品生产、经营企业违反本办法第七条规定的，给予警告，责令限期改正。<br><br>\r\n");
      out.write("第三十二条　有下列情形之一的，依照《药品管理法》第七十三条规定，没收违法销售的药品和违法所得，并处违法销售的药品货值金额2倍以上5倍以下的罚款：<br><br>\r\n");
      out.write("（一）药品生产、经营企业违反本办法第八条规定，在经药品监督管理部门核准的地址以外的场所现货销售药品的；<br><br>\r\n");
      out.write("（二）药品生产企业违反本办法第九条规定的；<br><br>\r\n");
      out.write("（三）药品生产、经营企业违反本办法第十五条规定的；<br><br>\r\n");
      out.write("（四）药品经营企业违反本办法第十七条规定的。<br><br>\r\n");
      out.write("第三十三条　药品生产、经营企业违反本办法第八条规定，在经药品监督管理部门核准的地址以外的场所储存药品的，按照《药品管理法实施条例》第七十四条的规定予以处罚。<br><br>\r\n");
      out.write("第三十四条　药品零售企业违反本办法第十一条第二款规定的，责令改正，给予警告；逾期不改正的，处以500元以下的罚款。<br><br>\r\n");
      out.write("第三十五条　违反本办法第十三条规定，药品生产、经营企业知道或者应当知道他人从事无证生产、经营药品行为而为其提供药品的，给予警告，责令改正，并处1万元以下的罚款，情节严重的，处1万元以上3万元以下的罚款。<br><br>\r\n");
      out.write("第三十六条　药品生产、经营企业违反本办法第十四条规定的，按照《药品管理法》第八十二条的规定予以处罚。<br><br>\r\n");
      out.write("第三十七条　违反本办法第十六条规定，药品经营企业购进或者销售医疗机构配制的制剂的，按照《药品管理法》第八十条规定予以处罚。<br><br>\r\n");
      out.write("第三十八条　药品零售企业违反本办法第十八条第一款规定的，责令限期改正，给予警告；逾期不改正或者情节严重的，处以1000元以下的罚款。<br><br>\r\n");
      out.write("违反本办法第十八条第二款规定，药品零售企业在执业药师或者其他依法经过资格认定的药学技术人员不在岗时销售处方药或者甲类非处方药的，责令限期改正，给予警告；逾期不改正的，处以1000元以下的罚款。<br><br>\r\n");
      out.write("第三十九条　药品生产、批发企业违反本办法第十九条规定，未在药品说明书规定的低温、冷藏条件下运输药品的，给予警告，责令限期改正；逾期不改正的，处以5000元以上2万元以下的罚款；有关药品经依法确认属于假劣药品的，按照《药品管理法》有关规定予以处罚。\r\n");
      out.write("药品生产、批发企业违反本办法第十九条规定，未在药品说明书规定的低温、冷藏条件下储存药品的，按照《药品管理法》第七十九条的规定予以处罚；有关药品经依法确认属于假劣药品的，按照《药品管理法》有关规定予以处罚。\r\n");
      out.write("第四十条　药品生产、经营企业违反本办法第二十条规定的，限期改正，给予警告；逾期不改正或者情节严重的，处以赠送药品货值金额2倍以下的罚款，但是最高不超过3万元。<br><br>\r\n");
      out.write("第四十一条　违反本办法第二十三条至第二十七条的，责令限期改正，情节严重的，给予通报。<br><br>\r\n");
      out.write("第四十二条　药品生产、经营企业违反本办法第二十一条、医疗机构违反本办法第二十八条规定，以邮售、互联网交易等方式直接向公众销售处方药的，责令改正，给予警告，并处销售药品货值金额2倍以下的罚款，但是最高不超过3万元。<br><br>\r\n");
      out.write("第四十三条　违反本办法第二十二条规定非法收购药品的，按照《药品管理法》第七十三条的规定予以处罚。<br><br>\r\n");
      out.write("第四十四条　药品监督管理部门及其工作人员玩忽职守，对应当予以制止和处罚的违法行为不予制止、处罚的，对直接负责的主管人员和其他直接责任人员给予行政处分；构成犯罪的，依法追究刑事责任。<br><br>\r\n");
      out.write("<h3>第五章　附则</h3><br>\r\n");
      out.write("\r\n");
      out.write("第四十五条　本办法所称药品现货销售，是指药品生产、经营企业或其委派的销售人员，在药品监督管理部门核准的地址以外的其他场所，携带药品现货向不特定对象现场销售药品的行为。<br><br>\r\n");
      out.write("第四十六条　实行特殊管理的药品、疫苗、军队用药品的流通监督管理，有关法律、法规、规章另有规定的，从其规定。<br><br>\r\n");
      out.write("第四十七条　本办法自2007年5月1日起施行。自本办法施行之日起，1999年8月1日实施的国家药品监督管理局《药品流通监督管理办法（暂行）》（国家药品监督管理局第7号令）同时废止。<br><br>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
