/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2015-06-17 12:28:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/authority/login_css.css\" type=\"text/css\" />\r\n");
      out.write("<title>智能药监管理系统</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    h1 {font-family: Georgia;\r\n");
      out.write("        font-size:50px;\r\n");
      out.write("        font-style:oblique;}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <h1 align=\"center\" style=\"color:black\"><br>智能药监管理系统</h1>\r\n");
      out.write("    <div id=\"login_area\">\r\n");
      out.write("        <div id=\"login_box\">\r\n");
      out.write("            <div id=\"login_form\">\r\n");
      out.write("              <form method=\"post\">\r\n");
      out.write("                  <div>\r\n");
      out.write("                                             用户名:<input type=\"text\" name=\"username\" class=\"username\" id=\"name\" /><br/>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div>\r\n");
      out.write("                                             密&nbsp;&nbsp;&nbsp;&nbsp;码:<input type=\"password\" name=\"password\" class=\"pwd\" id=\"pwd\"/><br/>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <br>\r\n");
      out.write("                <!--    <div id=\"pos_area\">\r\n");
      out.write("                                                                  身&nbsp;&nbsp;&nbsp;&nbsp;份:\r\n");
      out.write("                      <select style=\"width: 210px\">\r\n");
      out.write("                          <option>管理员</option>\r\n");
      out.write("                          <option>检品登记</option>\r\n");
      out.write("                          <option>检品检验</option>\r\n");
      out.write("                          <option>质保科管理</option>\r\n");
      out.write("                          <option>后勤保障</option>\r\n");
      out.write("                          <option>科室主任</option>\r\n");
      out.write("                          <option>业务管理</option>\r\n");
      out.write("                          <option>受权签字人</option>\r\n");
      out.write("                          <option>校对管理</option>\r\n");
      out.write("                          <option>最终检验</option>\r\n");
      out.write("                          <option>报告打印</option>\r\n");
      out.write("                      </select>\r\n");
      out.write("                  </div>   -->\r\n");
      out.write("\r\n");
      out.write("                  <div id=\"btn_area\">\r\n");
      out.write("                     <input type=\"submit\" class=\"login_btn\" id=\"login_sub\"  value=\"登  录\">&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"reset\" class=\"login_btn\" id=\"login_ret\" value=\"重 置\">\r\n");
      out.write("                  </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("          <br><br>\r\n");
      out.write("           <div align=\"center\" class=\"foot_last\">\r\n");
      out.write("              <p class=\"ftnav\">\r\n");
      out.write("                <a href=\"\" target=\"_blank\">关于我们</a>|\r\n");
      out.write("                   <a href=\"\" target=\"_blank\">联系我们</a>|\r\n");
      out.write("                  <a href=\"\" target=\"_blank\">资质许可</a>|\r\n");
      out.write("                  <a href=\"\" target=\"_blank\">在线客服</a>|\r\n");
      out.write("                  <a href=\"\" target=\"_blank\">在线招聘</a>|\r\n");
      out.write("                  <a href=\"\" target=\"_blank\">全部商品</a>|\r\n");
      out.write("                  <a href=\"\" target=\"_blank\">全部品牌</a>|\r\n");
      out.write("                  <a href=\"\" target=\"_blank\">热门关键词</a>|\r\n");
      out.write("                  <a href=\"\" target=\"_blank\">全部分类</a>|\r\n");
      out.write("                  <a href=\"\" target=\"_blank\">金象导航</a>\r\n");
      out.write("              </p>\r\n");
      out.write("              <p>版权所有：陕西省西安市药监局</p>\r\n");
      out.write("            <p>Copyright? 药监局 2015-2016， All Rights Reserved</p>\r\n");
      out.write("          </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
